### ISSUE TITLE
iOS 12.2 beta remote always turnoff sky-q box

### ISSUE THREAD

**Issue by francescob** [thomaspleasance/homebridge-sky-q#4]
The plugins work in the way I can turn sky q on and off from the Home app, but if I try to use the new ios 12.2 remote every action turn off the box
Is this a known problem?

**Comment by thomaspleasance** [comment]
I have fixed the bug it should be ok now

**Comment by francescob** [comment]
Yes, works now. Thank you
PS:
It may be interesting for you that this is working on an Italian SkyQ box
